name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-commitizen

      - name: Bump Version
        run: cz bump --files-only --yes

      - name: Get New Version
        run: echo "version=$(cz version --project)" >> "$GITHUB_ENV"

      - name: Push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: release ${{ env.version }}'
          commit_options: '--no-verify --signoff'
          file_pattern: cz.json CHANGELOG.md packages/pic/package.json
          tagging_message: '${{ env.version }}'

      - name: Generate Release Notes
        run: cz changelog --incremental --file-name RELEASE_NOTES.md
