name: Test (NodeJS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Test (NodeJS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-pnpm

      - uses: ./.github/actions/setup-dfx

      - name: Build
        run: pnpm run build

      - name: Start DFX
        run: dfx start --background

      - name: Create Example Canisters
        run: pnpm create:counter && pnpm create:clock && pnpm create:todo

      - name: Build Examples
        run: pnpm build:counter && pnpm build:clock && pnpm build:todo

      - name: Stop DFX
        run: dfx stop

      - name: Test Examples
        run: pnpm test:counter && pnpm test:clock && pnpm test:todo
