name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-bun

      - name: Setup DFX
        uses: dfinity/setup-dfx@main

      - name: Build
        run: bun run build

      - name: Build Examples
        run: bun build:examples

      - name: Test Examples
        run: bun test:examples
